### ISSUE TITLE
Typo in depth_img = depth_frame.reshape((kinect.depth_frame_desc.Height, kinect.depth_frame_desc.Width, 4)).astype(np.uint8) 

### ISSUE THREAD

**Issue by limgm** [KonstantinosAng/PyKinect2-Mapper-Functions#1]
Thanks for compiling this set of useful mapper functions!

I think the value 4 in this line https://github.com/KonstantinosAng/PyKinect2-Mapper-Functions/blob/bc63d39962c9df6fc7fac3eb2cf9bc48c1bb2c03/mapper.py#L58

should be changed to 1

**Comment by KonstantinosAng** [comment]
Yes, you are right, thank you very much. I will update it.

**Comment by limgm** [comment]
I think if the 1 is omitted from depth_img, 
```
depth_img = depth_frame.reshape((kinect.depth_frame_desc.Height, kinect.depth_frame_desc.Width)).astype(np.uint8)
```
then the subsequent two lines
```
align_depth_img = np.zeros((1080, 1920, 4), dtype=np.uint8)
align_depth_img[:, :] = depth_img[depthYs, depthXs, :]
```
would have to change to:
```
align_depth_img = np.zeros((1080, 1920), dtype=np.uint8)
align_depth_img[:, :] = depth_img[depthYs, depthXs]
```

**Comment by KonstantinosAng** [comment]
You are right i must have copied them from color_2_depth_space and forgot about them. I updated the code. Thanks again.
