### ISSUE TITLE
Mapping in the Original PyKinect

### ISSUE THREAD

**Issue by GameDungeon** [KonstantinosAng/PyKinect2-Mapper-Functions#13]
First, I know that this is for PyKinect2 and it doesn't work in the original one. I wish to do something similar for the original PyKinect, but all information on how to do it has seemed to have vanished. I'm asking here as you seem to have figured out how to do it in this version and I'm wondering if you could point me in the right direction. 

SDK for 1.8: https://learn.microsoft.com/en-us/previous-versions/windows/kinect-1.8/hh855347(v=ieb.10)
The pykinect docs seem to have been lost at some point.

**Comment by KonstantinosAng** [comment]
I think that the best library for the original Kinects is this one:

[Libfreenect](https://github.com/OpenKinect/libfreenect/)

It has support for windows, mac and linux and for [various languages](https://github.com/OpenKinect/libfreenect/tree/master/wrappers/python).

**Comment by GameDungeon** [comment]
thanks. I'll try that again I guess, originally it refused to work on my computer, but troubleshooting that is probably better than trying to basically write the pykinect lib from scratch.
