### ISSUE TITLE
Convertted depth image should be an uint16 array

### ISSUE THREAD

**Issue by cdowen** [KonstantinosAng/PyKinect2-Mapper-Functions#3]
Thanks for these functions! They are really useful.

However, in the depth_2_color_space function, the returned depth gets converted to uint8 which I think is not optimal.  The original data is in uint16 range and numpy astype may cause loss in precision, even plain erroneous depth value.

Best regards!

**Comment by KonstantinosAng** [comment]
As i don't have a Kinect device to test it now, i cannot be sure if the uint16 is fitted for the depth image. I remember when i tested it that the uint16 resulted in an error depth image but i may be wrong. You can test it out and make a pull request if you think that this is correct.

**Comment by cdowen** [comment]
I am pretty sure it's uint16. The C++ SDK uses UINT16 array to store the depth image. See [AccessUnderLyingBuffer](https://docs.microsoft.com/en-us/previous-versions/windows/kinect/dn791025(v=ieb.10)?redirectedfrom=MSDN) and [CopyFrameDataToArray](https://docs.microsoft.com/en-us/previous-versions/windows/kinect/dn758467(v=ieb.10)?redirectedfrom=MSDN). The error depth image might be due to visualization issues. Sometimes the uint16 data get clipped when visualization.

**Comment by KonstantinosAng** [comment]
Thanks for the update. I have changed the code to uint16 for the depth image and the aligned image.
